global using System.Collections.Immutable;
global using BackgroundUIUpdate.DataContracts;
global using BackgroundUIUpdate.DataContracts.Serialization;
global using BackgroundUIUpdate.Models;
global using BackgroundUIUpdate.Presentation;
global using BackgroundUIUpdate.Services.Caching;
global using BackgroundUIUpdate.Services.Endpoints;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
